CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(250),
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "AvatarUrl" character varying(500),
    "Gender" character varying(20),
    "Role" character varying(20) NOT NULL,
    "SubscriptionType" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "AiStylistHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Occasion" character varying(50),
    "Style" character varying(50),
    "Weather" character varying(50),
    "RecommendedOutfitData" text NOT NULL,
    "FeedbackRating" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_AiStylistHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AiStylistHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ClothingItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Color" character varying(50) NOT NULL,
    "Style" character varying(50) NOT NULL,
    "Season" character varying(50) NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ClothingItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClothingItems_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ClothingItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Outfits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Occasion" character varying(50),
    "Season" character varying(50),
    "IsFavorite" boolean NOT NULL,
    "CreatedByAi" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Outfits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Outfits_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OutfitItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OutfitId" integer NOT NULL,
    "ClothingItemId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_OutfitItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OutfitItems_ClothingItems_ClothingItemId" FOREIGN KEY ("ClothingItemId") REFERENCES "ClothingItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OutfitItems_Outfits_OutfitId" FOREIGN KEY ("OutfitId") REFERENCES "Outfits" ("Id") ON DELETE CASCADE
);

INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name", "UpdatedAt")
VALUES (1, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Áo thun, sơ mi, áo len, croptop', 1, TRUE, 'Tops', NULL);
INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name", "UpdatedAt")
VALUES (2, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Quần jeans, quần tây, chân váy, quần short', 2, TRUE, 'Bottoms', NULL);
INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name", "UpdatedAt")
VALUES (3, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Đầm liền thân, váy dài', 3, TRUE, 'Dresses', NULL);
INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name", "UpdatedAt")
VALUES (4, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Áo khoác, blazer, cardigan, hoodie', 4, TRUE, 'Outerwear', NULL);
INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name", "UpdatedAt")
VALUES (5, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Sneakers, giày tây, cao gót, sandals, boots', 5, TRUE, 'Shoes', NULL);
INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name", "UpdatedAt")
VALUES (6, TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Túi xách, thắt lưng, mũ nón, trang sức', 6, TRUE, 'Accessories', NULL);

CREATE INDEX "IX_AiStylistHistories_UserId" ON "AiStylistHistories" ("UserId");

CREATE UNIQUE INDEX "IX_Categories_Name" ON "Categories" ("Name");

CREATE INDEX "IX_ClothingItems_CategoryId" ON "ClothingItems" ("CategoryId");

CREATE INDEX "IX_ClothingItems_UserId" ON "ClothingItems" ("UserId");

CREATE INDEX "IX_OutfitItems_ClothingItemId" ON "OutfitItems" ("ClothingItemId");

CREATE INDEX "IX_OutfitItems_OutfitId" ON "OutfitItems" ("OutfitId");

CREATE INDEX "IX_Outfits_UserId" ON "Outfits" ("UserId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260910170904_InitialCreateSupabase', '8.0.10');

COMMIT;

