-- MYFITDAILY - Full Database Schema & Seed Data for Supabase PostgreSQL
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(250),
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "AvatarUrl" character varying(500),
    "Gender" character varying(20),
    "Role" character varying(20) NOT NULL,
    "SubscriptionType" character varying(20) NOT NULL,
    "Height" double precision,
    "Weight" double precision,
    "Chest" double precision,
    "Waist" double precision,
    "Hips" double precision,
    "BodyShape" character varying(50),
    "Age" integer,
    "AgeGroup" character varying(50),
    "SubscriptionExpiresAt" timestamp with time zone,
    "SubscriptionPeriod" character varying(20),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AiStylistHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Occasion" character varying(50),
    "Style" character varying(50),
    "Weather" character varying(50),
    "RecommendedOutfitData" text NOT NULL,
    "FeedbackRating" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_AiStylistHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AiStylistHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ClothingItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Color" character varying(50) NOT NULL,
    "Style" character varying(50) NOT NULL,
    "Season" character varying(50) NOT NULL,
    "ImageUrl" text NOT NULL,
    "Description" text,
    "Brand" character varying(100),
    "Size" character varying(20),
    "Price" numeric,
    "PriceFormatted" character varying(50),
    "AffiliateUrl" text,
    "OriginalUrl" text,
    "Platform" character varying(50),
    "IsAffiliate" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ClothingItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClothingItems_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ClothingItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Outfits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Occasion" character varying(50),
    "Season" character varying(50),
    "IsFavorite" boolean NOT NULL,
    "CreatedByAi" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Outfits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Outfits_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "OutfitItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OutfitId" integer NOT NULL,
    "ClothingItemId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_OutfitItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OutfitItems_ClothingItems_ClothingItemId" FOREIGN KEY ("ClothingItemId") REFERENCES "ClothingItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OutfitItems_Outfits_OutfitId" FOREIGN KEY ("OutfitId") REFERENCES "Outfits" ("Id") ON DELETE CASCADE
);

-- Seed Categories
INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name", "UpdatedAt")
VALUES 
    (1, NOW(), 'Áo thun, sơ mi, áo len, croptop', 1, TRUE, 'Tops', NULL),
    (2, NOW(), 'Quần jeans, quần tây, chân váy, quần short', 2, TRUE, 'Bottoms', NULL),
    (3, NOW(), 'Đầm liền thân, váy dài', 3, TRUE, 'Dresses', NULL),
    (4, NOW(), 'Áo khoác, blazer, cardigan, hoodie', 4, TRUE, 'Outerwear', NULL),
    (5, NOW(), 'Sneakers, giày tây, cao gót, sandals, boots', 5, TRUE, 'Shoes', NULL),
    (6, NOW(), 'Túi xách, thắt lưng, mũ nón, trang sức', 6, TRUE, 'Accessories', NULL)
ON CONFLICT ("Id") DO NOTHING;

-- Seed Demo Users
INSERT INTO "Users" ("Id", "Email", "PasswordHash", "FullName", "Gender", "Role", "SubscriptionType", "Height", "Weight", "Chest", "Waist", "Hips", "BodyShape", "CreatedAt")
VALUES 
    (1, 'test@myfitdaily.com', '$2a$11$q9hE9gC0G6y0e8.6g8WdNuH4n0y6rN0zU6fU2v6k5r6l.e8m6q7qy', 'Gentleman (Demo Nam)', 'Nam', 'User', 'Premium', 178, 70, 98, 76, 96, 'Tam giác ngược (Athletic)', NOW()),
    (2, 'demo@myfitdaily.com', '$2a$11$q9hE9gC0G6y0e8.6g8WdNuH4n0y6rN0zU6fU2v6k5r6l.e8m6q7qy', 'Fashionista (Demo Nữ)', 'Nữ', 'User', 'Premium', 165, 50, 84, 62, 90, 'Đồng hồ cát (Hourglass)', NOW())
ON CONFLICT ("Id") DO NOTHING;

-- Seed Curated Clothing Items (5 Items for Demo Nam)
INSERT INTO "ClothingItems" ("Id", "UserId", "CategoryId", "Name", "Color", "Style", "Season", "ImageUrl", "Description", "Brand", "Size", "Price", "PriceFormatted", "Platform", "IsAffiliate", "CreatedAt")
VALUES 
    (201, 1, 1, 'Áo ba lỗ Coolmate Relaxed', 'Nâu taupe', 'Minimal Street', 'Summer', '/assets/stylist/coolmate-tank-top.png', 'Áo ba lỗ relaxed màu taupe.', 'COOLMATE', 'M', 179000, '179K', 'Coolmate', FALSE, NOW()),
    (202, 1, 1, 'Sweatshirt Frozen.HN Studio', 'Đen', 'Streetwear', 'Fall / Winter', '/assets/stylist/frozen-sweatshirt.png', 'Sweatshirt cổ tròn form rộng màu đen.', 'FROZEN.HN', 'M', 263000, '263K', 'Frozen.HN', FALSE, NOW()),
    (205, 1, 1, 'Áo Sơ Mi Oxford Navy Slim-Fit', 'Xanh Navy', 'Smart Casual', 'AllSeason', '/assets/stylist/navy-shirt-essential.png', 'Áo sơ mi dài tay xanh navy phom dáng ôm vừa vặn.', 'ZARA MAN', 'M', 349000, '349K', 'Zara', FALSE, NOW()),
    (203, 1, 2, 'Quần suông dây rút Cream', 'Kem', 'Relaxed', 'AllSeason', '/assets/stylist/cream-relaxed-pants.png', 'Quần ống suông dây rút màu kem.', 'STYLIST EDIT', 'M', 320000, '320K', 'Curated', FALSE, NOW()),
    (204, 1, 5, 'Sneaker Retro Cream / Black', 'Kem / Đen', 'Retro', 'AllSeason', '/assets/stylist/retro-sneakers.png', 'Sneaker low-top retro với đế gum.', 'RETRO CLUB', '42', 450000, '450K', 'Curated', FALSE, NOW())
ON CONFLICT ("Id") DO NOTHING;

-- Seed Outfits
INSERT INTO "Outfits" ("Id", "UserId", "Name", "Description", "Occasion", "Season", "IsFavorite", "CreatedByAi", "CreatedAt")
VALUES 
    (301, 1, 'Cream & Black Signature', 'Sweatshirt đen, quần cream và sneaker retro: một set streetwear tối giản.', 'Casual', 'AllSeason', TRUE, FALSE, NOW()),
    (302, 1, 'Summer Relaxed Street', 'Áo ba lỗ taupe cùng quần suông cream và sneaker retro mát mẻ ngày hè.', 'Casual', 'Summer', TRUE, FALSE, NOW()),
    (303, 1, 'Smart Casual Navy Look', 'Áo sơ mi oxford xanh navy kết hợp quần suông màu kem và sneaker retro thanh lịch.', 'Formal', 'AllSeason', TRUE, FALSE, NOW())
ON CONFLICT ("Id") DO NOTHING;

-- Seed Outfit Items Link
INSERT INTO "OutfitItems" ("Id", "OutfitId", "ClothingItemId", "CreatedAt")
VALUES 
    (401, 301, 202, NOW()),
    (402, 301, 203, NOW()),
    (403, 301, 204, NOW()),
    (404, 302, 201, NOW()),
    (405, 302, 203, NOW()),
    (406, 302, 204, NOW()),
    (407, 303, 205, NOW()),
    (408, 303, 203, NOW()),
    (409, 303, 204, NOW())
ON CONFLICT ("Id") DO NOTHING;

COMMIT;
