-- MYFITDAILY - Full Database Schema & Seed Data for Supabase PostgreSQL
-- Production Ready & Synchronized with DbSeeder

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

-- 1. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(250),
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

-- 2. USERS TABLE
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "AvatarUrl" character varying(500),
    "Gender" character varying(20),
    "Role" character varying(20) NOT NULL DEFAULT 'User',
    "SubscriptionType" character varying(20) NOT NULL DEFAULT 'Free',
    "Height" double precision,
    "Weight" double precision,
    "Chest" double precision,
    "Waist" double precision,
    "Hips" double precision,
    "BodyShape" character varying(50),
    "Age" integer,
    "AgeGroup" character varying(50),
    "SubscriptionExpiresAt" timestamp with time zone,
    "SubscriptionPeriod" character varying(20),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- 3. AI STYLIST HISTORIES TABLE
CREATE TABLE IF NOT EXISTS "AiStylistHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Occasion" character varying(50),
    "Style" character varying(50),
    "Weather" character varying(50),
    "RecommendedOutfitData" text NOT NULL,
    "FeedbackRating" integer,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_AiStylistHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AiStylistHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- 4. CLOTHING ITEMS TABLE
CREATE TABLE IF NOT EXISTS "ClothingItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Color" character varying(50) NOT NULL,
    "Style" character varying(50) NOT NULL,
    "Season" character varying(50) NOT NULL,
    "ImageUrl" text NOT NULL,
    "Description" text,
    "Brand" character varying(100),
    "Size" character varying(20),
    "Price" numeric,
    "PriceFormatted" character varying(50),
    "AffiliateUrl" text,
    "OriginalUrl" text,
    "Platform" character varying(50),
    "IsAffiliate" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ClothingItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClothingItems_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ClothingItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- 5. OUTFITS TABLE
CREATE TABLE IF NOT EXISTS "Outfits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Occasion" character varying(50),
    "Season" character varying(50),
    "IsFavorite" boolean NOT NULL DEFAULT false,
    "CreatedByAi" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Outfits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Outfits_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- 6. OUTFIT ITEMS LINK TABLE
CREATE TABLE IF NOT EXISTS "OutfitItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OutfitId" integer NOT NULL,
    "ClothingItemId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_OutfitItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OutfitItems_ClothingItems_ClothingItemId" FOREIGN KEY ("ClothingItemId") REFERENCES "ClothingItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OutfitItems_Outfits_OutfitId" FOREIGN KEY ("OutfitId") REFERENCES "Outfits" ("Id") ON DELETE CASCADE
);

-- 7. PAYMENT TRANSACTIONS TABLE (SEPAY INTEGRATION)
CREATE TABLE IF NOT EXISTS "PaymentTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "OrderCode" character varying(50),
    "PlanId" character varying(50),
    "BillingCycle" character varying(20),
    "Amount" numeric,
    "Status" character varying(30) DEFAULT 'Pending',
    "SePayTransactionId" character varying(100),
    "PaidAt" timestamp with time zone,
    "BankBrandName" character varying(50),
    "AccountNumber" character varying(50),
    "TransactionContent" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PaymentTransactions_OrderCode" ON "PaymentTransactions" ("OrderCode");

-- 8. SEED CATEGORIES
INSERT INTO "Categories" ("Id", "CreatedAt", "Description", "DisplayOrder", "IsActive", "Name", "UpdatedAt")
VALUES 
    (1, NOW(), 'Áo thun, sơ mi, polo, len', 1, TRUE, 'Tops', NULL),
    (2, NOW(), 'Quần jeans, quần tây, shorts, kaki', 2, TRUE, 'Bottoms', NULL),
    (3, NOW(), 'Đầm liền thân, váy dài', 3, TRUE, 'Dresses', NULL),
    (4, NOW(), 'Áo khoác, blazer, cardigan, hoodie', 4, TRUE, 'Outerwear', NULL),
    (5, NOW(), 'Sneakers, giày tây, cao gót, sandals', 5, TRUE, 'Shoes', NULL),
    (6, NOW(), 'Túi xách, thắt lưng, mũ nón, kính', 6, TRUE, 'Accessories', NULL)
ON CONFLICT ("Id") DO NOTHING;

-- 9. SEED ACCOUNTS (testnam, testnu, admin)
-- Passwords: 'testnam', 'testnu', 'admin'
INSERT INTO "Users" ("Id", "Email", "PasswordHash", "FullName", "Gender", "Role", "SubscriptionType", "Height", "Weight", "Chest", "Waist", "Hips", "BodyShape", "Age", "AgeGroup", "CreatedAt")
VALUES 
    (1, 'testnam', '$2a$11$GgT/l9d2P4P0qZkWaP6G6eHh40a1j9eM0y5sS2fR5q8tZ1v3k7g0u', 'Gentleman (Test Nam)', 'Nam', 'User', 'Premium', 178, 70, 98, 78, 95, 'Tam giác ngược', 24, 'GenZ', NOW()),
    (2, 'testnu', '$2a$11$GgT/l9d2P4P0qZkWaP6G6eHh40a1j9eM0y5sS2fR5q8tZ1v3k7g0u', 'Fashionista (Test Nữ)', 'Nữ', 'User', 'Premium', 165, 52, 88, 64, 92, 'Đồng hồ cát', 22, 'GenZ', NOW()),
    (3, 'admin', '$2a$11$GgT/l9d2P4P0qZkWaP6G6eHh40a1j9eM0y5sS2fR5q8tZ1v3k7g0u', 'Ban Quản Trị Hệ Thống', 'Nam', 'Admin', 'PremiumPlus', 175, 68, 96, 76, 94, 'Cân đối', 26, 'Millennial', NOW())
ON CONFLICT ("Id") DO NOTHING;

-- 10. SEED CLOTHING INVENTORY (TOPS, BOTTOMS, SHOES)
INSERT INTO "ClothingItems" ("Id", "UserId", "CategoryId", "Name", "Color", "Style", "Season", "ImageUrl", "Description", "Brand", "Size", "Price", "PriceFormatted", "Platform", "IsAffiliate", "CreatedAt")
VALUES 
    (201, 1, 1, 'Áo ba lỗ Coolmate Relaxed', 'Nâu taupe', 'Minimal Street', 'Summer', '/assets/stylist/coolmate-tank-top.png', 'Áo ba lỗ relaxed màu taupe.', 'COOLMATE', 'M', 179000, '179K', 'Coolmate', FALSE, NOW()),
    (202, 1, 1, 'Sweatshirt Frozen.HN Studio', 'Đen', 'Streetwear', 'Fall / Winter', '/assets/stylist/frozen-sweatshirt.png', 'Sweatshirt cổ tròn form rộng màu đen.', 'FROZEN.HN', 'M', 263000, '263K', 'Frozen.HN', FALSE, NOW()),
    (203, 1, 1, 'Áo Sơ Mi Oxford Navy Slim-Fit', 'Xanh Navy', 'Smart Casual', 'AllSeason', '/assets/stylist/navy-shirt-essential.png', 'Áo sơ mi dài tay xanh navy phom dáng ôm vừa vặn.', 'ZARA MAN', 'M', 349000, '349K', 'Zara', FALSE, NOW()),
    (204, 1, 1, 'Áo Sơ Mi Sọc Kẻ Dài Tay Boxy', 'Xanh Blue / Sọc', 'Korean Casual', 'AllSeason', '/assets/clothes/shirt_stripe_blue.png', 'Áo sơ mi dài tay form boxy rộng kẻ sọc xanh nhã nhặn, chất vải cotton thô mát.', 'DAILY EDIT', 'L', 320000, '320K', 'Daily Edit', FALSE, NOW()),
    (205, 1, 1, 'Áo Polo Dệt Kim Cable Knit Trắng', 'Trắng', 'Old Money', 'Summer', '/assets/clothes/polo_cable_knit_white.png', 'Áo polo cộc tay dệt kim họa tiết xoắn thừng cable knit màu trắng sang trọng.', 'POLO CLUB', 'M', 380000, '380K', 'Polo Club', FALSE, NOW()),
    (206, 1, 1, 'Áo Polo Phối Vai Đen Be Cát', 'Be Cát / Đen', 'Smart Casual', 'Summer', '/assets/clothes/polo_pazzin_beige.png', 'Áo polo cộc tay cổ bẻ phối sọc vai đen trên nền be cát thể thao thanh lịch.', 'PAZZIN', 'L', 290000, '290K', 'Pazzin', FALSE, NOW()),
    (207, 1, 2, 'Quần suông dây rút Cream', 'Kem', 'Relaxed', 'AllSeason', '/assets/stylist/cream-relaxed-pants.png', 'Quần ống suông dây rút màu kem.', 'STYLIST EDIT', 'M', 320000, '320K', 'Curated', FALSE, NOW()),
    (208, 1, 2, 'Quần Tây Xếp Ly Dáng Suông Xám Than', 'Xám Than Chì', 'Sartorial', 'AllSeason', '/assets/clothes/trousers_pleated_grey.png', 'Quần âu xếp ly dáng suông đứng phom phẳng phiu màu xám than chì lịch sự.', 'TAILOR LAB', 'M', 390000, '390K', 'Tailor Lab', FALSE, NOW()),
    (209, 1, 2, 'Quần Short Jean Cạp Chun Wash Xanh', 'Xanh Denim Wash', 'Streetwear', 'Summer', '/assets/clothes/shorts_denim_wash.png', 'Quần short jean denim lưng thun cạp chun thoải mái wash màu bụi bặm trẻ trung.', 'DENIM CO', 'M', 260000, '260K', 'Denim Co', FALSE, NOW()),
    (210, 1, 5, 'Sneaker Retro Cream / Black', 'Kem / Đen', 'Retro', 'AllSeason', '/assets/stylist/retro-sneakers.png', 'Sneaker low-top retro với đế gum.', 'RETRO CLUB', '42', 450000, '450K', 'Curated', FALSE, NOW()),
    (211, 1, 5, 'Sneaker Chunky Trắng Xanh Navy', 'Trắng / Xanh Navy', 'Streetwear', 'AllSeason', '/assets/clothes/sneaker_chunky_white_blue.png', 'Sneaker đế độn chunky màu trắng phối cổ và dây xanh navy trẻ trung năng động.', 'STREET LAB', '42', 420000, '420K', 'Street Lab', FALSE, NOW()),
    (212, 1, 5, 'Giày Tây Derby Da Đen Đế Răng Cưa', 'Đen', 'Sartorial', 'AllSeason', '/assets/clothes/derby_leather_black.png', 'Giày tây Derby da bò đen bóng đế răng cưa chunky thời thượng, phù hợp phối quần âu hoặc jeans.', 'CRAFT DERBY', '42', 590000, '590K', 'Craft Derby', FALSE, NOW())
ON CONFLICT ("Id") DO NOTHING;

-- 11. SEED SIGNATURE OUTFITS
INSERT INTO "Outfits" ("Id", "UserId", "Name", "Description", "Occasion", "Season", "IsFavorite", "CreatedByAi", "CreatedAt")
VALUES 
    (301, 1, 'Cream & Black Signature', 'Sweatshirt đen, quần cream và sneaker retro: một set streetwear tối giản.', 'Casual', 'AllSeason', TRUE, FALSE, NOW()),
    (302, 1, 'Summer Relaxed Street', 'Áo ba lỗ taupe cùng quần suông cream và sneaker retro mát mẻ ngày hè.', 'Casual', 'Summer', TRUE, FALSE, NOW()),
    (303, 1, 'Smart Casual Navy Look', 'Áo sơ mi oxford xanh navy kết hợp quần suông màu kem và sneaker retro thanh lịch.', 'Formal', 'AllSeason', TRUE, FALSE, NOW())
ON CONFLICT ("Id") DO NOTHING;

-- 12. SEED OUTFIT ITEMS
INSERT INTO "OutfitItems" ("Id", "OutfitId", "ClothingItemId", "CreatedAt")
VALUES 
    (401, 301, 202, NOW()),
    (402, 301, 207, NOW()),
    (403, 301, 210, NOW()),
    (404, 302, 201, NOW()),
    (405, 302, 207, NOW()),
    (406, 302, 210, NOW()),
    (407, 303, 203, NOW()),
    (408, 303, 207, NOW()),
    (409, 303, 210, NOW())
ON CONFLICT ("Id") DO NOTHING;

COMMIT;
